# Generated by Django 4.2.10 on 2024-08-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription_courses_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-id',), 'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
    ]
