# Generated by Django 4.2.10 on 2024-08-20 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='product',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Название группы'),
            preserve_default=False,
        ),
    ]
