# Generated by Django 4.2.10 on 2024-08-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_group_product_group_student_group_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='product',
        ),
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
    ]
