# Generated by Django 4.2.10 on 2024-08-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_group_product_remove_group_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
