# Generated by Django 4.2.10 on 2024-08-20 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_group_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='client',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
