# Generated by Django 4.2.10 on 2024-08-20 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_group_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
